version: "3"

services:
  next-app:
    container_name: next-app
    build:
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:example@db:5432/postgres?schema=public
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: pk_test_YWxsb3dlZC1iZWV0bGUtNTIuY2xlcmsuYWNjb3VudHMuZGV2JA
      CLERK_SECRET_KEY: sk_test_wApHrctQeOxKi9OpqD3i0HIuMtZIwK6WwV36rOQiIr
      NEXT_PUBLIC_APP_HOST: http://127.0.0.1
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    user: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "psql", "-l" ]
      interval: 1s
      timeout: 5s
      retries: 10
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
  lb:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    # depends_on:
    #  - next-app

