import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {ClerkProvider, currentUser} from "@clerk/nextjs";
import React from "react";
import registerUser from "@/lib/user/register";
import '@radix-ui/themes/styles.css';
import {Theme, ThemePanel} from "@radix-ui/themes";
import Header from "@/components/chunks/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await registerUser()
  return (

      <html lang="en">
          <head>
              <title>Splittle</title>
          </head>
        <body className={inter.className}>
        <ClerkProvider>
          <Theme appearance="dark" accentColor="gray" panelBackground="solid" radius="large">
            { /* <ThemePanel /> */}
            <Header/>
            {
              children
            }
          </Theme>
        </ClerkProvider>
        </body>
      </html>
  );
}
