import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {ClerkProvider, currentUser} from "@clerk/nextjs";
import React from "react";
import registerUser from "@/lib/user/register";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await registerUser()
  return (

      <html lang="en">
        <body className={inter.className}>
        <ClerkProvider>
          {
            children
          }
        </ClerkProvider>
        </body>
      </html>
  );
}
